version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - "echo Install Phase: `date`"
      - npm install -g yarn
      - yarn install --production=false
  build:
    commands:
      - "echo Build Phase: `date`"
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
